- name: Install Sauce Codes
  git: repo=https://github.com/openhealthcare/{{ item }} 
       dest=/usr/lib/ohc/{{ item }} 

  with_items: 
      - opal
      - elcid


# name: elCID project setup

- name: Create elCID Virtualenv
  command: virtualenv  /home/vagrant/.virtualenvs/elcid
  
- name: Install elCID Dependencies
  command: /home/vagrant/.virtualenvs/elcid/bin/pip install -r /usr/lib/ohc/elcid/requirements.txt

- name: Uninstall elCID OPAL
  command: /home/vagrant/.virtualenvs/elcid/bin/pip uninstall opal

- name: Install development opal
  command: /home/vagrant/.virtualenvs/elcid/bin/python /usr/lib/ohc/opal/setup.py develop